name: DebugBuild

on:
  pull_request :
    branches : [ main ]
  push :
    branches : [ main ]

jobs:
  build:
    runs-on : ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Create local.properties with api access token
        env:
          API_ACCESS_TOKEN: ${{ secrets.API_ACCESS_TOKEN }}
        run: echo API_ACCESS_TOKEN="API_ACCESS_TOKEN" > ./local.properties

      - name: Grant execute permissions for gradlew
        run: chmod +x ./gradlew

      - name: Setup Gradle Cache
        uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-cleanup: true

      - name: Run Tests with Gradle
        run: ./gradlew test

      - name: Build with Gradle
        run : ./gradlew build